### ISSUE TITLE
Where to install in Max 7

### ISSUE THREAD

**Issue by heaversm** [Syphon/Jitter#2]
Hi - Max 7 no longer has a "patches" folder. How do we install in the new version?

**Comment by xhain** [comment]
Same issue here. Are there any precompiled versions of jit.gl.syphonserver.mxo available?

**Comment by DavidJFreeman** [comment]
Did anyone ever solve this? I've been successful in compiling the .mxo files needed using the .xcodeworkspace file, and have been able to get the externals visible in Max 7, but the objects themselves don't work. They change colour and don't have any inlets or outlets when added to a patch. Any suggestions?

**Comment by vade** [comment]
Just add the directory you have externals in to your file path.
